### ISSUE TITLE
Incomplete dots during unlocking

### ISSUE THREAD

**Issue by mtaipe** [DigiByte-Core/digibytewallet-ios#9]
When unlocking the wallet using the PIN the numeric keypad covers the lower part of the blue dots that represents each number entered. This is just an aesthetic issue on an iPhone SE running iOS 12.3.1.  The DigiByte iOS version is 1.0.9 build 1542. This issue was present in the previous build as well. See picture below.
<img width="371" alt="image" src="https://user-images.githubusercontent.com/31449449/59888365-e1721280-93f9-11e9-8fba-f986a36e45ea.png">

**Comment by SmartArray** [comment]
Thank you for your feedback!

Always hard to keep track of all devices. 😌

**Comment by mtaipe** [comment]
Just to report that build 1549 fix this problem, you may close this issue. See below for proof.
<img width="297" alt="image" src="https://user-images.githubusercontent.com/31449449/59965219-ab3dab80-953d-11e9-90c1-f56276f9bda9.png">
